---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: metallb
  namespace: metallb
spec:
  interval: 1h
  url: https://metallb.github.io/metallb
  timeout: 5m
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: metallb
  namespace: metallb
spec:
  interval: 30m
  chart:
    spec:
      chart: metallb
      version: '0.0.0'
      sourceRef:
        kind: HelmRepository
        name: metallb
        namespace: metallb
      interval: 30m
  install:
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5