---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: victoriametrics
  namespace: monitoring
spec:
  interval: 1h
  url: https://victoriametrics.github.io/helm-charts/
  timeout: 5m
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: victoriametrics
  namespace: monitoring
spec:
  interval: 30m
  chart:
    spec:
      chart: victoria-metrics-k8s-stack
      version: '0.55.2'
      sourceRef:
        kind: HelmRepository
        name: victoriametrics
        namespace: monitoring
      interval: 30m
  install:
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    global:
      cluster:
        dnsDomain: homelab.local
    victoria-metrics-operator:
      operator:
        disable_prometheus_converter: true
    vmsingle:
      enabled: false
    vmcluster:
      enabled: true
    kubeControllerManager:
      enabled: false
    kubeScheduler:
      enabled: false
    kubeEtcd:
      enabled: true
      service:
        port: 2381
        targetPort: 2381
      vmScrape:
        spec:
          endpoints:
            scheme: http