---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: metrics-server
  namespace: monitoring
spec:
  interval: 1h
  url: https://kubernetes-sigs.github.io/metrics-server/
  timeout: 5m
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: metrics-server
  namespace: monitoring
spec:
  interval: 30m
  chart:
    spec:
      chart: metrics-server
      version: '3.12.2'
      sourceRef:
        kind: HelmRepository
        name: metrics-server
        namespace: monitoring
      interval: 30m
  install:
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    args:
      - --kubelet-insecure-tls