---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: harbor
  namespace: harbor
spec:
  interval: 1h
  url: https://helm.goharbor.io
  timeout: 5m
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: harbor
  namespace: harbor
spec:
  interval: 30m
  chart:
    spec:
      chart: harbor
      version: '1.17.0'
      sourceRef:
        kind: HelmRepository
        name: harbor
        namespace: harbor
      interval: 30m
  install:
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    expose:
      type: loadBalancer
      tls:
        auto:
          commonName: "harbor"