all:
  hosts:
    mini1:
      ansible_host: 192.168.0.101
      ip: 192.168.0.101
      access_ip: 192.168.0.101
    mini2:
      ansible_host: 192.168.0.102
      ip: 192.168.0.102
      access_ip: 192.168.0.102
    mini3:
      ansible_host: 192.168.0.103
      ip: 192.168.0.103
      access_ip: 192.168.0.103
    pc:
      ansible_host: 192.168.0.104
      ip: 192.168.0.104
      access_ip: 192.168.0.104
  children:
    kube_control_plane:
      hosts:
        mini1:
        mini2:
        mini3:
    kube_node:
      hosts:
        pc:
    etcd:
      hosts:
        mini1:
        mini2:
        mini3:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
    calico_rr:
      hosts: {}
