apiVersion: kubevirt.io/v1
kind: KubeVirt
metadata:
  name: kubevirt
  namespace: kubevirt
spec:
  certificateRotateStrategy: {}
  configuration:
    network:
      binding:
        macvtap:
          domainAttachmentType: "tap"
    developerConfiguration:
      featureGates: 
        - NetworkBindingPlugins
  customizeComponents: {}
  imagePullPolicy: IfNotPresent
  workloadUpdateStrategy: {}