name: Lint YAML

on:
  pull_request:
    branches:
      - main

jobs:
  validate:
    name: YAML Linting
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Get changed YAML files
      id: changes
      run: |
        git fetch origin main
        CHANGED=$(git diff --name-only origin/main...HEAD -- 'apps/**/*.yaml' 'apps/**/*.yml')
        echo "$CHANGED"
        echo "changed_files<<EOF" >> $GITHUB_OUTPUT
        echo "$CHANGED" >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT

    - name: Run yamllint
      if: steps.changed.outputs.changed_files != ''
      uses: frenck/action-yamllint@v1
      with:
        files: ${{ steps.changed.outputs.changed_files }}

    - name: Run kubeconform
      if: steps.changed.outputs.changed_files != ''
      uses: docker://ghcr.io/yannh/kubeconform:latest
      with:
        entrypoint: /kubeconform
        args: -strict -summary ${{ steps.changed.outputs.changed_files }}