name: Lint YAML

on:
  pull_request:
    branches:
      - main

jobs:
  validate:
    name: YAML Linting
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Get changed YAML files
      id: changes
      run: |
        git fetch origin main
        CHANGED=$(git diff --name-only origin/main...HEAD -- 'apps/**/*.yaml' 'apps/**/*.yml')
        echo "$CHANGED"
        echo "changed_files<<EOF" >> $GITHUB_OUTPUT
        echo "$CHANGED" >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT

    - name: Install linters
      run: |
        sudo apt-get update
        sudo apt-get install -y yamllint
        curl -sSLo kubeconform.tar.gz https://github.com/yannh/kubeconform/releases/latest/download/kubeconform-linux-amd64.tar.gz
        tar -xzf kubeconform.tar.gz
        sudo mv kubeconform /usr/local/bin/

    - name: Run yamllint
      if: steps.changes.outputs.changed_files != ''
      run: |
        echo "${{ steps.changes.outputs.changed_files }}" | while read file; do
          if [[ -f "$file" ]]; then
            echo "Linting YAML syntax: $file"
            yamllint "$file"
          fi
        done

    - name: Run kubeconform
      if: steps.changes.outputs.changed_files != ''
      run: |
        echo "${{ steps.changes.outputs.changed_files }}" | while read file; do
          if [[ -f "$file" ]]; then
            echo "Validating Kubernetes manifest: $file"
            kubeconform -strict -summary "$file"
          fi
        done
